

export const MENUITEMS = [
  {
    icon: (<i className="side-menu__icon bx bx-home"></i>),
    path: '/controlpanel',
    type: 'link',
    active: false,
    selected: false,
    dirchange: false,
    title: 'Control Panel'

  },

  {
    icon: (<i className="bx bx-layer side-menu__icon"></i>),
    type: "sub",
    Name: '',
    active: false,
    selected: false,
    dirchange: false,
    title: "Group",
    badge: '',
    badgetxt: '',
    class: '',
    children: [
      {
        path: '/groupform',
        title: "Add Group",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/grouplist',
        title: "View Group",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/grouppermission',
        title: "Group Permission",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
    ],
  },
  {
    icon: (<i className="ri ri-chat-settings-line side-menu__icon"></i>),
    type: "sub",
    Name: '',
    active: false,
    selected: false,
    dirchange: false,
    title: "DFH Members",
    badge: '',
    badgetxt: '',
    class: '',
    children: [
      {
        path: '/memberform',
        title: "Add Member",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/memberlist',
        title: "View Member",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
    ],
  },

  {
    icon: (<i className="bx bx-table side-menu__icon"></i>),
    type: "sub",
    Name: '',
    active: false,
    selected: false,
    dirchange: false,
    title: "Registered Users",
    badge: '',
    badgetxt: '',
    class: '',
    children: [
      {
        path: '/registeruser',
        title: "All Users",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/doctordetails',
        title: "Doctor Details",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/patientdetails',
        title: "Patient Details",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },  
    ],
  },
  {
    icon: (<i className="bx bx-bar-chart-alt side-menu__icon"></i>),
    type: "sub",
    Name: '',
    active: false,
    selected: false,
    dirchange: false,
    title: "HealthCare Provider",
    badge: '',
    badgetxt: '',
    class: '',
    children: [
  
      {
        path: '/hospitaldetails',
        title: "Hospital Details",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/pharmacydetails',
        title: "Pharmacy Details",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/clinicdetails',
        title: "Clinic Details",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/diagnosticdetails',
        title: "Diagnostic Details",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/stemcelltherapydetails',
        title: "StemCell Terapy Details",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
      {
        path: '/allied',
        title: "Allied HealthCare",
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
      },
    ],
  },
  {
    icon: (<i className="bx bx-lock-alt side-menu__icon"></i>),
    path: '/termscondition',
    title: "Terms and Conditions",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
//   {
//     icon: (<i className="bx bx-lock-alt side-menu__icon"></i>),
//     path: '/adminaccount',
//     title: "Admin Accounts",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="bx bx-medal side-menu__icon"></i>),
//     path: '/speciality',
//     title: "Doctor's Speciality",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="fe fe-eye side-menu__icon"></i>),
//     path: '/patientfollowup',
//     title: "Patient FollowUp",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },

//   {
//     icon: (<i className="ri ri-chat-2-line side-menu__icon"></i>),
//     path: '/reviews',
//     title: "Patient Feedback",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },

//   {
//     icon: (<i className="ti ti-armchair side-menu__icon"></i>),
//     path: '/appointmentlist',
//     title: "Appointment",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="fe fe-alert-triangle side-menu__icon"></i>),
//     path: '/appointmentcancel',
//     title: "Appointment Cancel",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="fe fe-airplay side-menu__icon"></i>),
//     path: '/appointment',
//     title: "Face to Face Appointment",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },


//   {
//     icon: (<i className="ti ti-color-picker side-menu__icon"></i>),
//     path: '/labtest',
//     title: "Lab For Test",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="bx bx-layer side-menu__icon"></i>),
//     path: '/labstatus',
//     title: "Lab Order Status",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="bx bx-box side-menu__icon"></i>),
//     path: '/pharmacyorder',
//     title: "Pharmacy Order",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="ri ri-edit-line side-menu__icon"></i>),
//     path: '/pharmacyorderstatus',
//     title: "Pharmacy Order Status",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },

//   {
//     icon: (<i className="ti ti-activity-heartbeat side-menu__icon"></i>),
//     type: "sub",
//     Name: '',
//     active: false,
//     selected: false,
//     dirchange: false,
//     title: "HealthCare Roles",
//     badge: '',
//     badgetxt: '',
//     class: '',
//     children: [
//       {
//         path: '/listhealthcareroles',
//         title: "List HealthCare Roles",
//         type: "link",
//         active: false,
//         selected: false,
//         dirchange: false,
//       },
//       {
//         path: '/addhealthcareroles',
//         title: "Add HealthCare Roles",
//         type: "link",
//         active: false,
//         selected: false,
//         dirchange: false,
//       },
//     ],
//   },

//   {
//     icon: (<i className="ri ri-edit-line side-menu__icon"></i>),
//     path: '/healthcaremember',
//     title: "HealthCare Member",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="bx bx-receipt side-menu__icon"></i>),
//     path: '/secondopnionform',
//     title: "Second Opnion Form",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="bx bx-bar-chart-alt side-menu__icon"></i>),
//     type: "sub",
//     Name: '',
//     active: false,
//     selected: false,
//     dirchange: false,
//     title: "Discount Packages",
//     badge: '',
//     badgetxt: '',
//     class: '',
//     children: [
//       {
//         path: '/addpackages',
//         title: "Add Package",
//         type: "link",
//         active: false,
//         selected: false,
//         dirchange: false,
//       },
//       {
//         path: '/packagelist',
//         title: "Package List",
//         type: "link",
//         active: false,
//         selected: false,
//         dirchange: false,
//       },
//     ],
//   },
//   {
//     icon: (<i className="bi bi-cash-coin side-menu__icon"></i>),
//     path: '/cashback',
//     title: "Cash Back Offer",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="bx bx-gift side-menu__icon"></i>),
//     path: '/financialreport',
//     title: "Financial Report",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="las la-map side-menu__icon"></i>),
//     path: '/language',
//     title: "Add Language",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="ti ti-bell side-menu__icon"></i>),
//     path: '/emailsubscriber',
//     title: "Email Subscriber",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },
//   {
//     icon: (<i className="las la-envelope side-menu__icon"></i>),
//     path: '/email',
//     title: "Send Email To Users",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },


//   {
//     icon: (<i className="fe fe-camera side-menu__icon"></i>),
//     path: '/profile',
//     title: "Profile",
//     type: "link",
//     active: false,
//     selected: false,
//     dirchange: false,
//   },

// ];

];